[v,f] =  read_off('Armadillo.off');
vMat = v';
fMat = f';
%trimesh(fMat, vMat(:,1), vMat(:,2), vMat(:,3));
%mu = 10;
%Pot = zeros(size(vMat,1),1);
%Pot(vMat(:,2)>=20) = mu;
patch('Faces',fMat,'Vertices',vMat,'FaceVertexCData',Pot,'FaceColor','interp','EdgeColor','k','EdgeAlpha',0.1);
axis equal;
xlabel('X');
ylabel('Y');
zlabel('Z');
title('3D Mesh Plot');
view(180,270);
colorbar;
%centroid = mean(V1);
%V_shif = V1 - centroid;
%V_scal = 2*V_shif;
